<?php
session_start();
require_once __DIR__ . '/../includes/auth.php'; require_once __DIR__ . '/../includes/csrf.php'; require_once __DIR__ . '/../includes/helpers.php'; require_once __DIR__ . '/../db.php'; require_admin_auth();
$pdo=db(); $id=trim((string)($_GET['id']??''));
$client=['name'=>'','website_url'=>'','notification_email'=>'','bot_name'=>'AI Assistant','welcome_message'=>'','system_prompt'=>'','business_context'=>'','fallback_message'=>'','lead_capture_enabled'=>1,'lead_capture_mode'=>'after_interest','status'=>'active','monthly_message_limit'=>1000];
if($id){$st=$pdo->prepare('SELECT * FROM chatbot_clients WHERE id=:id');$st->execute(['id'=>$id]);$client=$st->fetch()?:$client;}
if($_SERVER['REQUEST_METHOD']==='POST' && csrf_validate($_POST['csrf_token']??'')){
  $f=['name','website_url','notification_email','bot_name','welcome_message','system_prompt','business_context','fallback_message','lead_capture_mode','status','monthly_message_limit'];
  foreach($f as $k){$client[$k]=trim((string)($_POST[$k]??''));}
  $client['lead_capture_enabled']=isset($_POST['lead_capture_enabled'])?1:0;
  if(!$id){$id=random_id(16);$client['public_key']=bin2hex(random_bytes(16));$sql='INSERT INTO chatbot_clients (id,public_key,name,website_url,notification_email,bot_name,welcome_message,system_prompt,business_context,fallback_message,lead_capture_enabled,lead_capture_mode,status,monthly_message_limit,created_at,updated_at) VALUES (:id,:public_key,:name,:website_url,:notification_email,:bot_name,:welcome_message,:system_prompt,:business_context,:fallback_message,:lead_capture_enabled,:lead_capture_mode,:status,:monthly_message_limit,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))';}
  else {$sql='UPDATE chatbot_clients SET name=:name,website_url=:website_url,notification_email=:notification_email,bot_name=:bot_name,welcome_message=:welcome_message,system_prompt=:system_prompt,business_context=:business_context,fallback_message=:fallback_message,lead_capture_enabled=:lead_capture_enabled,lead_capture_mode=:lead_capture_mode,status=:status,monthly_message_limit=:monthly_message_limit,updated_at=UTC_TIMESTAMP(6) WHERE id=:id';}
  $stmt=$pdo->prepare($sql);$stmt->execute($client+['id'=>$id]);header('Location: clients.php');exit;
}
?><!doctype html><html><body><h1>Client</h1><form method='post'><input type='hidden' name='csrf_token' value='<?=e(csrf_token())?>'><?php foreach(['name','website_url','notification_email','bot_name','welcome_message','fallback_message','monthly_message_limit'] as $k):?><label><?=$k?><input name='<?=$k?>' value='<?=e((string)$client[$k])?>'></label><br><?php endforeach;?><label>lead_capture_enabled<input type='checkbox' name='lead_capture_enabled' value='1' <?=((int)$client['lead_capture_enabled']===1?'checked':'')?>></label><br><label>lead_capture_mode<select name='lead_capture_mode'><option>before_chat</option><option selected>after_interest</option><option>manual</option></select></label><br><label>status<select name='status'><option>active</option><option>inactive</option></select></label><br><label>system_prompt<textarea name='system_prompt'><?=e((string)$client['system_prompt'])?></textarea></label><br><label>business_context<textarea name='business_context'><?=e((string)$client['business_context'])?></textarea></label><br><button>Save</button></form></body></html>
